# Generated by Django 4.0.4 on 2022-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(choices=[('aPositive', 'A+'), ('aNegative', 'A-'), ('bPositive', 'B+'), ('bNegative', 'B-'), ('abPositive', 'AB+'), ('abNegative', 'AB-'), ('oPositive', 'O+'), ('oNegative', 'O-')], default=None, max_length=20, null=True),
        ),
    ]
